apiVersion: v1
items:
- apiVersion: v1
  data:
    database: cG9zdGdyZXM=
    password: cGFzc3dvcmQ=
    username: cG9zdGdyZXM=
  kind: Secret
  metadata:
    name: prod-db-secret
    namespace: default
  type: Opaque
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
