apiVersion: v1
kind: Pod
metadata:
  labels:
    run: postgres
  name: postgres
  namespace: default
spec:
  containers:
  - image: postgres
    imagePullPolicy: Always
    name: postgres
    ports:
    - containerPort: 5432
    env:
    - name: POSTGRES_PASSWORD
      value: "password"
    - name: POSTGRES_USER
      value: "postgres"
    - name: POSTGRES_DB
      value: "postgres"      
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-d8rbg
      readOnly: true
  volumes:
  - name: kube-api-access-d8rbg
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
spec:
  selector:
    run: postgres 
  ports:
  - port: 5432
    targetPort: 5432
